# Generated by scripts/build_fiscal_manifest.py. DO NOT EDIT.
from __future__ import annotations

from typing import Literal, TypeAlias

FISCAL_DATASET_IDS = (
    "imss_base_rates",
    "imss_ceav",
    "imss_modalidad_10",
    "imss_modalidad_40",
    "isr_payroll",
    "minimum_wage",
    "uma",
)

FiscalDatasetId: TypeAlias = Literal[
    "imss_base_rates",
    "imss_ceav",
    "imss_modalidad_10",
    "imss_modalidad_40",
    "isr_payroll",
    "minimum_wage",
    "uma",
]

__all__ = ["FISCAL_DATASET_IDS", "FiscalDatasetId"]
